MODEL:
    name: "EDVR"
    format: "png"
    num_frames: 5
    center: 2
    num_filters: 128 #64
    deform_conv_groups: 8
    front_RBs: 5
    back_RBs: 40 #10
    predeblur: False
    HR_in: False
    w_TSA: True #False

INFER:
    scale: 4
    crop_size: 256
    interval_list: [1]
    random_reverse: False
    number_frames: 5
    batch_size: 1
    file_root: "/workspace/color/input_frames"
    #gt_root: "/workspace/video_test/video/data/dataset/edvr/REDS4/GT"
    use_flip: False
    use_rot: False
