MODEL:
    name: "EDVR"
    format: "png"
    num_frames: 5
    center: 2
    num_filters: 64
    deform_conv_groups: 8
    front_RBs: 5
    back_RBs: 10
    predeblur: False
    HR_in: False
    w_TSA: False

TRAIN:
    epoch: 45
    use_gpu: True
    num_gpus: 8
    scale: 4
    crop_size: 256
    interval_list: [1]
    random_reverse: False
    number_frames: 5
    batch_size: 32
    #file_root: "/mnt/sungaofeng/edvr/paddle/video/data/dataset/edvr/REDS/train_sharp_bicubic/X4"
    file_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS/train_sharp_bicubic/X4"
    #gt_root: "/mnt/sungaofeng/edvr/paddle/video/data/dataset/edvr/REDS/train_sharp"
    gt_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS/train_sharp"
    use_flip: True
    use_rot: True
    base_learning_rate: 0.0004
    l2_weight_decay: 0.0
    T_periods: [150000, 150000, 150000, 150000] # for cosine annealing restart
    restarts: [150000, 300000, 450000] # for cosine annealing restart
    weights: [1, 1, 1] # for cosine annealing restart
    eta_min: 1e-7 # for cosine annealing restart
    num_reader_threads: 8
    buf_size: 1024
    fix_random_seed: False

VALID:
    scale: 4
    crop_size: 256
    interval_list: [1]
    random_reverse: False
    number_frames: 5
    batch_size: 32 #256
    #file_root: "/mnt/sungaofeng/edvr/paddle/video/data/dataset/edvr/REDS4/GT"
    file_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS4/sharp_bicubic"
    #gt_root: "/mnt/sungaofeng/edvr/paddle/video/data/dataset/edvr/REDS4/sharp_bicubic"
    gt_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS4/GT"
    use_flip: False
    use_rot: False

TEST:
    scale: 4
    crop_size: 256
    interval_list: [1]
    random_reverse: False
    number_frames: 5
    batch_size: 1
    #file_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS4/sharp_bicubic"
    #gt_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS4/GT"
    file_root: "/mnt/sungaofeng/edvr/paddle/video/data/dataset/edvr/REDS4/sharp_bicubic"
    gt_root: "/mnt/sungaofeng/edvr/paddle/video/data/dataset/edvr/REDS4/GT"
    use_flip: False
    use_rot: False

INFER:
    scale: 4
    crop_size: 256
    interval_list: [1]
    random_reverse: False
    number_frames: 5
    batch_size: 1
    file_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS4/sharp_bicubic"
    gt_root: "/ssd1/vis/sungaofeng/edvr/mmsr/datasets/REDS4/GT"
    use_flip: False
    use_rot: False
